name: Plan

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/CODEOWNERS'
    branches:
      - main

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Source Code
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: actions/github-script@v6
      name: Records update plan
      env:
        CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let out = '';
          const options = {
            listeners: {
              stdout: (data) => {
                out += data.toString();
              },
              stderr: (data) => {
                out += data.toString();
              }
            }
          };
          let planStatus = 'OK';
          try {
            await exec.exec('go', ['run', 'cmd/cafe/main.go'], options);
          } catch (e) {
            console.log('---')
            console.error(e)
            planStatus = 'FAILED'
          }
          let body = `### Cafe Plan:\n<details><summary>Status: ${planStatus}</summary>\n\n\`\`\`\n${out}\n\`\`\`\n</details>`
          await github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
          if (planStatus == 'FAILED') {
            process.exit(1);
          }