name: Update CF records

on:
  push:
    branches: [ "main" ]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run cafe
      env:
        CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
        CAFE_CONFIRM: 'yes'
      run: go run cmd/cafe/main.go
